/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICasinoTreasury,
  ICasinoTreasuryInterface,
} from "../ICasinoTreasury";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_adr",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_nTokens",
        type: "uint256",
      },
    ],
    name: "UpdateBalancesAdd",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_adr",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_nTokens",
        type: "uint256",
      },
    ],
    name: "UpdateBalancesSub",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_nTokens",
        type: "uint256",
      },
    ],
    name: "TaxPayment",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_adr",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawError",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_nDollars",
        type: "uint256",
      },
    ],
    name: "calcTokensFromDollars",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_nTokens",
        type: "uint256",
      },
    ],
    name: "calcDollars",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tokenAdr",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICasinoTreasury__factory {
  static readonly abi = _abi;
  static createInterface(): ICasinoTreasuryInterface {
    return new utils.Interface(_abi) as ICasinoTreasuryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICasinoTreasury {
    return new Contract(address, _abi, signerOrProvider) as ICasinoTreasury;
  }
}
