/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { ILiqPair, ILiqPairInterface } from "../ILiqPair";

const _abi = [
  {
    inputs: [],
    name: "getReserves",
    outputs: [
      {
        internalType: "uint112",
        name: "_reserve0",
        type: "uint112",
      },
      {
        internalType: "uint112",
        name: "_reserve1",
        type: "uint112",
      },
      {
        internalType: "uint32",
        name: "_blockTimestampLast",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ILiqPair__factory {
  static readonly abi = _abi;
  static createInterface(): ILiqPairInterface {
    return new utils.Interface(_abi) as ILiqPairInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILiqPair {
    return new Contract(address, _abi, signerOrProvider) as ILiqPair;
  }
}
