/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IPancakePair, IPancakePairInterface } from "../IPancakePair";

const _abi = [
  {
    inputs: [],
    name: "sync",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPancakePair__factory {
  static readonly abi = _abi;
  static createInterface(): IPancakePairInterface {
    return new utils.Interface(_abi) as IPancakePairInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPancakePair {
    return new Contract(address, _abi, signerOrProvider) as IPancakePair;
  }
}
