/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IUniswapV3, IUniswapV3Interface } from "../IUniswapV3";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "commands",
        type: "bytes",
      },
      {
        internalType: "bytes[]",
        name: "inputs",
        type: "bytes[]",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IUniswapV3__factory {
  static readonly abi = _abi;
  static createInterface(): IUniswapV3Interface {
    return new utils.Interface(_abi) as IUniswapV3Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUniswapV3 {
    return new Contract(address, _abi, signerOrProvider) as IUniswapV3;
  }
}
