/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface AuthInterface extends utils.Interface {
  functions: {
    "authorize(address)": FunctionFragment;
    "unauthorize(address)": FunctionFragment;
    "isOwner(address)": FunctionFragment;
    "isAuthorized(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "authorize"
      | "unauthorize"
      | "isOwner"
      | "isAuthorized"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "authorize", values: [string]): string;
  encodeFunctionData(functionFragment: "unauthorize", values: [string]): string;
  encodeFunctionData(functionFragment: "isOwner", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isAuthorized",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "authorize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unauthorize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  owner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface Auth extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AuthInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    /**
     * Authorize address. Owner only
     */
    authorize(
      adr: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Remove address' authorization. Owner only
     */
    unauthorize(
      adr: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Check if address is owner
     */
    isOwner(account: string, overrides?: CallOverrides): Promise<[boolean]>;

    /**
     * Return address' authorization status
     */
    isAuthorized(adr: string, overrides?: CallOverrides): Promise<[boolean]>;

    /**
     * Transfer ownership to new address. Caller must be owner. Leaves old owner authorized
     */
    transferOwnership(
      adr: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  /**
   * Authorize address. Owner only
   */
  authorize(
    adr: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Remove address' authorization. Owner only
   */
  unauthorize(
    adr: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Check if address is owner
   */
  isOwner(account: string, overrides?: CallOverrides): Promise<boolean>;

  /**
   * Return address' authorization status
   */
  isAuthorized(adr: string, overrides?: CallOverrides): Promise<boolean>;

  /**
   * Transfer ownership to new address. Caller must be owner. Leaves old owner authorized
   */
  transferOwnership(
    adr: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    /**
     * Authorize address. Owner only
     */
    authorize(adr: string, overrides?: CallOverrides): Promise<void>;

    /**
     * Remove address' authorization. Owner only
     */
    unauthorize(adr: string, overrides?: CallOverrides): Promise<void>;

    /**
     * Check if address is owner
     */
    isOwner(account: string, overrides?: CallOverrides): Promise<boolean>;

    /**
     * Return address' authorization status
     */
    isAuthorized(adr: string, overrides?: CallOverrides): Promise<boolean>;

    /**
     * Transfer ownership to new address. Caller must be owner. Leaves old owner authorized
     */
    transferOwnership(adr: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address)"(
      owner?: null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(owner?: null): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    /**
     * Authorize address. Owner only
     */
    authorize(
      adr: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Remove address' authorization. Owner only
     */
    unauthorize(
      adr: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Check if address is owner
     */
    isOwner(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Return address' authorization status
     */
    isAuthorized(adr: string, overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Transfer ownership to new address. Caller must be owner. Leaves old owner authorized
     */
    transferOwnership(
      adr: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    /**
     * Authorize address. Owner only
     */
    authorize(
      adr: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Remove address' authorization. Owner only
     */
    unauthorize(
      adr: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Check if address is owner
     */
    isOwner(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Return address' authorization status
     */
    isAuthorized(
      adr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Transfer ownership to new address. Caller must be owner. Leaves old owner authorized
     */
    transferOwnership(
      adr: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
