name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    # defaults:
    #     run:
    #       working-directory: ./CASINO_DAPP/casino-dapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        working-directory: ./CASINO_DAPP/casino-dapp
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        working-directory: ./CASINO_DAPP/casino-dapp
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        working-directory: ./CASINO_DAPP/casino-dapp
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }} --debug
      - name: Deploy Project Artifacts to Vercel
        working-directory: ./CASINO_DAPP/casino-dapp
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}